variable "app_name" {}
variable "app_environment" {}
variable "image_tag" {}
variable "repository_name" {}
variable "ecsTaskExecutionRole_arn" {}
variable "aws_region" {}
variable "private_subnet" {}
variable "public_subnet" {}
variable "vpc_id" {}